## Advantages of Numpy Array:
1. Allow several mathematical opperation
2. Faster Opperation

List vs Array Numpy - Time Taken

In [3]:
#time taken by a list
from time import process_time

In [4]:
my_list = [i for i in range(10000)]
start_time = process_time()
print(start_time)
my_list = [i+5 for i in my_list]
end_time = process_time()
print(end_time)
print(end_time - start_time)

3.046369406
3.047338004
0.0009685980000000427


In [5]:
import numpy as np
array = np.array([i for i in range(10000)])
start_time = process_time()
print(start_time)
array += 5
end_time = process_time()
print(end_time)
print(end_time - start_time)

3.068107071
3.068954152
0.0008470809999998608


## Numpy Array
1D : Vector <br>
2D : Matrix <br>
3D : Tensol <br>

In [ ]:
list = [1,2,3,4,5]
print(list) # comma separated
type(list)

[1, 2, 3, 4, 5]


list

In [ ]:
a=np.array(list)
print(a) #no comma
type(a)
print(a.shape)

[1 2 3 4 5]
(5,)


Initial Placeholder

In [ ]:
#create a numpy array of zeros
b=np.zeros((4,5),dtype=int) #default float , ones twos
print(b)
print(b.shape)
print(b.size)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
(4, 5)
20


In [ ]:
import pandas as pd
df=pd.DataFrame(b)
df

,0,1,2,3,4
0,0,0,0,0,0
1,0,0,0,0,0
2,0,0,0,0,0
3,0,0,0,0,0


In [ ]:
#array of a particular value
d=np.full((3,4),6)
print(d)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [ ]:
#create an identity matrix
e=np.eye(4)
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
#create numpy array random values
np.random.seed(42)
f=np.random.random((3,4)) #flaot
g=np.random.randint(10,100,(3,4)) #int
print(f)
print("Int: ")
print(g)

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]
Int: 
[[39 47 11 73]
 [69 30 42 85]
 [67 31 98 58]]


In [11]:
#array of evently spaces values --> specifying the values required
h=np.linspace(10,30,5)
print(h)


[10. 15. 20. 25. 30.]


In [ ]:
#array of evently spaces values --> specifying the valuesstep
i=np.arange(10,30,3) # start to n-1
print(i)
i.dtype

[10 13 16 19 22 25 28]


dtype('int64')

## Mathematical Opperation

In [ ]:
l1=[1,2,3,4] #liist
l2=[5,6,7]
print(l1+l2) #contanite

[1, 2, 3, 4, 5, 6, 7]


In [ ]:

# Convert lists to numpy arrays
arrl1 = np.array([1,2,3])
arrl2 = np.array([3,4,6])
arrl1 + arrl2


array([4, 6, 9])

### Transpose

### Reshaping